name       : bisq
version    : 0.6.7
release    : 3
source     :
    - https://github.com/bisq-network/bisq/archive/v0.6.7.tar.gz : 10a5c325232d2b6c650bb17450273335c5fed3c99fd06273dcc831f2c0f5b98c
license    : AGPL-3.0-or-later
component  : network.web
summary    : Decentralized Bitcoin exchange
description: |
    Bisq is an open-source desktop application that allows you to buy and sell Bitcoins in exchange for national currencies, or alternative cryptocurrencies.
networking : yes
builddeps  :
    - apache-maven
    - openjfx-8
rundeps    :
    - openjfx-8
build      : |
    mvn -Dmaven.repo.local=$workdir/repo -X -DskipTests -Dmaven.javadoc.skip=true package
install    : |
    install -Dm00644 gui/target/shaded.jar $installdir/usr/share/bisq/bisq.jar
    install -Dm00755 $pkgfiles/bisq.sh $installdir/usr/bin/bisq
    cp -a gui/target/lib $installdir/usr/share/bisq

    install -Dm00644 package/linux/icon.png $installdir/usr/share/pixmaps/bisq.png
    install -Dm00644 $pkgfiles/bisq.desktop -t $installdir/usr/share/applications
