name       : bisq
version    : 1.5.4
release    : 5
source     :
    - git|https://github.com/bisq-network/bisq.git : v1.5.4 # requires a Git repository for LFS
license    : AGPL-3.0-or-later
component  : network.web
summary    : Decentralized Bitcoin exchange
description: |
    Bisq is an open-source desktop application that allows you to buy and sell Bitcoins in exchange for national currencies, or alternative cryptocurrencies.
networking : yes
builddeps  :
    - git-lfs
    - openjdk-11
rundeps    :
    - openjdk-11
setup      : |
    git lfs install
    git lfs pull
build      : |
    export JAVA_HOME=/usr/lib64/openjdk-11
    export GRADLE_USER_HOME=$workdir/.gradle

    # tests will always fail, so disable them with -x test
    ./gradlew --no-daemon build -x test
install    : |
    install -dm00755 $installdir/usr/bin/
    install -dm00644 $installdir/usr/share/bisq/lib/

    cp -R lib/* $installdir/usr/share/bisq/lib/

    install -Dm00755 bisq-* $installdir/usr/share/bisq/

    pushd $installdir/usr/share/bisq/
    for FILE in bisq-*; do
        cp $pkgfiles/java-shim.sh $installdir/usr/bin/$FILE
        echo "/usr/share/bisq/$FILE \"\$@\"" >> $installdir/usr/bin/$FILE
        chmod +x $installdir/usr/bin/$FILE
    done
    popd

    install -Dm00644 desktop/package/linux/icon.png $installdir/usr/share/pixmaps/bisq.png
    install -Dm00644 $pkgfiles/bisq.desktop -t $installdir/usr/share/applications
