name       : bisq
version    : 0.6.1
release    : 1
source     :
    - https://github.com/bisq-network/exchange/archive/v0.6.1.tar.gz : ccadf3b4a2954566987528d5cb2e5e15615ffe4e6652e15f519d9d001cafe760
license    : AGPL-3.0
component  : network.web
summary    : The decentralized bitcoin exchange
description: |
    Bisq is an open-source desktop application that allows you to buy and sell bitcoins in exchange for national currencies, or alternative crypto currencies.
networking : yes
builddeps  :
    - apache-maven
    - openjfx-8
rundeps    :
    - openjfx-8
build      : |
    mvn clean package -Dmaven.repo.local=$workdir/repo -X -DskipTests -Dmaven.javadoc.skip=true
install    : |
    install -Dm755 gui/target/shaded.jar $installdir/usr/share/java/bisq/shaded.jar
    install -dm644 $installdir/usr/share/java/bisq/lib
    install -Dm644 gui/target/lib/bcpg-jdk15on.jar $installdir/usr/share/java/bisq/lib
    install -Dm644 gui/target/lib/bcprov-jdk15on.jar $installdir/usr/share/java/bisq/lib
    install -Dm644 package/linux/icon.png $installdir/usr/share/pixmaps/bisq.png
    install -Dm755 $pkgfiles/bisq.sh $installdir/usr/bin/bisq
    install -Dm644 $pkgfiles/bisq.desktop $installdir/usr/share/applications/bisq.desktop
